services:
  faunex-api:
    build:
      context: .
      dockerfile: Faunex.Api/Dockerfile
    container_name: faunex-api
    expose:
      - "8080"
    ports:
      - "5000:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ConnectionStrings__DefaultConnection: ${FAUNEX_CONNECTIONSTRING}
      FAUNEX_JWT_ISSUER: ${FAUNEX_JWT_ISSUER}
      FAUNEX_JWT_AUDIENCE: ${FAUNEX_JWT_AUDIENCE}
      FAUNEX_JWT_SIGNING_KEY: ${FAUNEX_JWT_SIGNING_KEY}
      FAUNEX_SUPERADMIN_PASSWORD: ${FAUNEX_SUPERADMIN_PASSWORD}
    volumes:
      - dataprotection_keys:/root/.aspnet/DataProtection-Keys
    depends_on:
      - db

  faunex-web:
    build:
      context: .
      dockerfile: Faunex.Web/Dockerfile
    container_name: faunex-web
    expose:
      - "8080"
    ports:
      - "5001:8080"
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      ASPNETCORE_URLS: http://+:8080
      ApiSettings__BaseUrl: http://faunex-api:8080
    volumes:
      - dataprotection_keys:/root/.aspnet/DataProtection-Keys
    depends_on:
      - faunex-api

  db:
    image: postgres:16
    container_name: faunex-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    expose:
      - "5432"

volumes:
  postgres_data:
  dataprotection_keys:
